version: '3.9'

services:
    db:
        image: postgres:latest
        restart: always
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=django
            - POSTGRES_USER=django
            - POSTGRES_DB=django
        networks:
            - back_db

    backend:
        image: localhost:5000/back
        command: python3 manage.py runserver 0.0.0.0:8000
        restart: always
        ports:
            - 8000:8000
        environment:
            - POSTGRES_NAME=django
            - POSTGRES_USER=django
            - POSTGRES_PASSWORD=django
        networks:
            - front
            - back_db
        ports:
            - "8000:8000"
        depends_on:
            - db

    web:
        image: localhost:5000/front
        restart: always
        ports:
            - 80:80
        networks:
            - front
        depends_on:
            - backend

networks:
  back_db:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"

  front:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.1.0/24"
